import { nextui } from "@nextui-org/react";
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/ui/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
        "open-sans": ["Open Sans", "sans-serif"],
      },
      colors: {
        bgColorLeft: "var(--bgColorLeft)",
        bgColorRight: "var(--bgColorRight)",
        bgButtonAccesible: "var(--bg--ButtonAccesible)",
        textButtonAccesible: "var(--text--ButtonAccesible)",
        bgSelectTheme: "var(--bg--SelectTheme)",
        textSelectTheme: "var(--text--SelectTheme)",
        labelInputText: "var(--label--inputText)",
        bgInputText: "var(--bg--InputTextColor)",
        focusColorInput: "var(--focus--ColorInput)",
        focusBgInput: "var(--focus--BgInput))",
        bgButtonFill: "var(--bg--ButonFill)",
        textButtonFill: "var(--text--ButtonFill)",
        bgButtonFillHover: "var(--bg--ButtonFillHover)",
        textButtonFillHover: "var(--text--ButtonFillHover)",
        textLabel: "var(--label--Label)",
        textRegisterLabel: "var(--text--RegisterLabel)",
        textForgotPassword: "var(--text-ForgotPassword)",
        primary: {
          100: "var(--primary--100)",
          150: "var(--primary--150)",
          200: "var(--primary--200)",
          250: "var(--primary--250)",
          300: "var(--primary--300)",
          350: "var(--primary--350)",
          400: "var(--primary--400)",
          450: "var(--primary--450)",
          500: "var(--primary--500)",
          550: "var(--primary--550)",
          DEFAULT: "var(--primary--600)",
          650: "var(--primary--650)",
          700: "var(--primary--700)",
          750: "var(--primary--750)",
        },
        secondary: {
          100: "var(--secondary--100)",
          150: "var(--secondary--150)",
          200: "var(--secondary--200)",
          250: "var(--secondary--250)",
          300: "var(--secondary--300)",
          350: "var(--secondary--250)",
          400: "var(--secondary--400)",
          450: "var(--secondary--450)",
          DEFAULT: "var(--secondary--500)",
          550: "var(--secondary--550)",
          600: "var(--secondary--600)",
          650: "var(--secondary--650)",
          700: "var(--secondary--700)",
          750: "var(--secondary--750)",
        },
        tertiary: {
          100: "var(--tertiary--100)",
          150: "var(--tertiary--150)",
          200: "var(--tertiary--200)",
          250: "var(--tertiary--250)",
          300: "var(--tertiary--300)",
          350: "var(--tertiary--350)",
          400: "var(--tertiary--400)",
          450: "var(--tertiary--450)",
          DEFAULT: "var(--tertiary--500)",
        },
        default: {},
      },
    },
  },
};
export default config;
