import { LoadingProvider } from "@/libs/contexts/loadingContext";
import { ModalProvider } from "@/libs/contexts/modalContext";
import Providers from "@/libs/contexts/providers";
import { ToastProvider } from "@/libs/contexts/toastContext";
import AccessibilityButton from "@/ui/components/buttons/AccessibilityButton";
import type { Metadata } from "next";
import "reflect-metadata";
import "regenerator-runtime/runtime";
import "../ui/globals.css";

export const metadata: Metadata = {
  title: "BookView",
  description: "Generated by create next app",
  applicationName: "BookView",
  authors: [{ name: "Luis Moreira" }],
  creator: "Luis Moreira",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <LoadingProvider>
            <ModalProvider>
              <ToastProvider>
                {children}
                <AccessibilityButton />
              </ToastProvider>
            </ModalProvider>
          </LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
