import 'regenerator-runtime/runtime';
import { LoadingProvider } from "@/libs/contexts/loadingContext";
import Providers from "@/libs/contexts/providers";
import { ToastProvider } from "@/libs/contexts/toastContext";
import AccessibilityButton from "@/ui/components/buttons/AccessibilityButton";
import type { Metadata } from "next";
import "../ui/globals.css";

export const metadata: Metadata = {
  title: "BookView",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        <Providers>
          <LoadingProvider>
            <ToastProvider>
              {children}
              <AccessibilityButton />
            </ToastProvider>
          </LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
